parameters:
#    parameter_name: value

services:
    formation_oss.job.manager:
        class: AppBundle\Manager\JobManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@logger'

    formation_oss.category.manager:
        class: AppBundle\Manager\CategoryManager
        arguments:
            - '@doctrine.orm.entity_manager'
    formation_oss.company.manager:
        class: AppBundle\Manager\CompanyManager
        arguments:
            - '@doctrine.orm.entity_manager'

    fomation_oss.address.manager:
        class: AppBundle\Manager\AddressManager
        arguments:
            - '@doctrine.orm.entity_manager'

    formation_oss.object_saver:
        class: AppBundle\Saver\ObjectSaver
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'

    formation_oss.mobile_detector:
        class: AppBundle\Detector\MobileDetector

    formation_oss.request_listerners:
        class: AppBundle\Listeners\RequestListener
        arguments:
            - '@formation_oss.mobile_detector'
            - '@router'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: analyzeRequest }

    formation_oss.storage_event.subscriber:
        class: AppBundle\Listeners\StorageEventSubscriber
        tags:
            - { name: kernel.event_subscriber }



